// AUTOMATICALLY GENERATED BY BUILDINC v0.2.363 TOOL
// LAST BUILD (CMAKE): 2024-08-07 18:20:45

module;
#include <cstdint>

export module deckard_build;
export namespace deckard_build::build
{
	 // You can modify major and minor
	constexpr uint32_t major = 0;
	constexpr uint32_t minor = 0;

	 // Do not modify these
	constexpr uint32_t patch = 5621;
	
	constexpr uint32_t version = major * 100000 + minor * 10000 + patch;
	constexpr uint64_t random_seed = 0x9893cf49aaa21b17;
	
	constexpr char version_string[] = "v0.0.5621";
	constexpr char build_time_string[] = "2024-08-07 18:20:45";
	constexpr char phrase[] = "trustful-ecosystem-shaking";
	constexpr char calver[] = "2024.32.5621";
	constexpr char uuid[] = "305B8A96-37A9-4AED-AB77-E38FA709A670";

	// Copy paste to import to your project
	/*
		constexpr auto major = deckard_build::major;
		constexpr auto minor = deckard_build::minor;
		constexpr auto patch = deckard_build::patch;
		constexpr auto version = deckard_build::version;
		constexpr auto random_seed = deckard_build::random_seed;
			
		constexpr auto version_string = deckard_build::version_string;
		constexpr auto build_time_string = deckard_build::build_time_string;
		constexpr auto phrase = deckard_build::phrase;
		constexpr auto calver = deckard_build::calver;
		constexpr auto uuid = deckard_build::uuid;
	*/
}
