// AUTOMATICALLY GENERATED BY BUILDINC v0.2.363 TOOL
// LAST BUILD (CMAKE): 2024-07-02 17:16:38

module;
#include <cstdint>

export module dbc;
export namespace dbc::build
{
	 // You can modify major and minor
	constexpr uint32_t major = 0;
	constexpr uint32_t minor = 0;

	 // Do not modify these
	constexpr uint32_t patch = 4802;
	
	constexpr uint32_t version = major * 100000 + minor * 10000 + patch;
	constexpr uint64_t random_seed = 0x1e09d13f30ddba16;
	
	constexpr char version_string[] = "v0.0.4802";
	constexpr char build_time_string[] = "2024-07-02 17:16:38";
	constexpr char phrase[] = "prodigy-confused-precision";
	constexpr char calver[] = "2024.27.4802";
	constexpr char uuid[] = "6CF0417B-8909-478B-BA98-65879A46D499";

	// Copy paste to import to your project
	/*
		constexpr auto major = dbc::major;
		constexpr auto minor = dbc::minor;
		constexpr auto patch = dbc::patch;
		constexpr auto version = dbc::version;
		constexpr auto random_seed = dbc::random_seed;
			
		constexpr auto version_string = dbc::version_string;
		constexpr auto build_time_string = dbc::build_time_string;
		constexpr auto phrase = dbc::phrase;
		constexpr auto calver = dbc::calver;
		constexpr auto uuid = dbc::uuid;
	*/
}
